@accessToken = eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzM2MzQyNzcsImlhdCI6MTc3MzYzMzk3Nywic3ViIjoiMDE5Y2QxNTQtOWMxZC03MjhkLWEyYjktOWEyNWIyY2I2NjNiIn0.yqC57J19N6udmHSU5egWl61ux0IKOf5CgxYGw6kb3-SZ_1EzZaIKLB66pblGIuShR8hDBfssv3GS3EPviAKGyQ
### Retrieve Image
GET http://localhost:8080/images/019cd177-02b5-73d7-9818-961bc5c96804
Authorization: Bearer {{accessToken}}

### List Images
GET http://localhost:8080/images/
Authorization: Bearer {{accessToken}}

### Upload Image
POST http://localhost:8080/images/
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./test.png
------Boundary--

### Transform Image
POST http://localhost:8080/images/019cd177-02b5-73d7-9818-961bc5c96804/transform
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "rotate": {
    "angle":180
  },
  "format": "png"
}
