@accessToken = eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzMxMjI4OTgsImlhdCI6MTc3MzEyMjgzOCwic3ViIjoiMDE5Y2QxNTQtOWMxZC03MjhkLWEyYjktOWEyNWIyY2I2NjNiIn0.0q553BJY9Fv21jdoXI9VOb1WjatrgpspPHeejiIhvw9EGLeqL0G21VHFFajgYXj_vgRL8wSa5q6RxF9rhdLUpg
### Retrieve Image
GET http://localhost:8080/images/019cd177-02b5-73d7-9818-961bc5c96804
Authorization: Bearer {{accessToken}}

### Upload Image
POST http://localhost:8080/images/
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./test.png
------Boundary--

### Transform Image
POST http://localhost:8080/images/019cd177-02b5-73d7-9818-961bc5c96804/transform
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "rotate": {
    "angle":180
  },
  "format": "png"
}
