### Retrieve Image
GET http://localhost:8080/images/019cc1f0-6e55-7d28-a3d7-64b40b11cfa7
Content-Type: multipart/form-data; boundary=----Boundary

### Upload Image
POST http://localhost:8080/images/
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./test.png
------Boundary--

### Transform Image
POST http://localhost:8080/images/019cc1db-2e84-7890-85c1-b5d273400d08/transform
Content-Type: application/json

{
  "rotate": {
    "angle":180
  },
  "format": "png"
}
