@accessToken = eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzMxMjQ4NjYsImlhdCI6MTc3MzEyNDU2Niwic3ViIjoiMDE5Y2QxNTQtOWMxZC03MjhkLWEyYjktOWEyNWIyY2I2NjNiIn0.7qft6nIQTEOE7kAo5nQY6fFbS1DkW7sIOXIZHLQzgdxQc9a5J3INDDx-6JkHm0CS8jWTle-SyekMBM-EIEj_Zw

### Check
GET http://localhost:8080/auth/check
Authorization: Bearer {{accessToken}}

### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Refresh Token
POST http://localhost:8080/auth/refresh
Cookie: refresh_token=576cdb1000762af550159b37556a7aa63cfa9c49b026b98c479d1baa136cfdb8; Path=/auth/refresh; Max-Age=604800; HttpOnly; SameSite=Strict


### Logout
POST http://localhost:8080/auth/logout
Content-Type: application/json

{
  "refresh_token": "your_refresh_token_here"
}